services:
  mongo:
    image: mongo:4.2.5
    ports:
      - '127.0.0.1:27017:27017'
  myapp:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
      DOCKER_DB: true
    ports:
      - '8080:5000'
      - '6789:6789'
    volumes:
      - ./:/app/logs
    depends_on:
      - mongo
