services:
  mongo:
    image: mongo:4.2.5
  myapp:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
      DOCKER_DB: true
    ports:
      - '8080:5000'
    volumes:
      - ./:/app/logs
    depends_on:
      - mongo